[#3420] disable editor when hidden
openscad/openscad pull request #3423
Opened 2020-08-27 07:35 UTC by eltonlaw

Addresses https://github.com/openscad/openscad/issues/3420

- Setting the active editor to read only when hidden 94cc6b4 
- If an autocomplete is being shown, cancel it 2b470a0

2020-08-28 09:10 UTC, t-paul requested changes
I think that's actually a Qt bug. It might even be fixed as I can't reproduce the issue on Debian/Testing with Qt5.14.2. There's a similar sounding issue https://bugreports.qt.io/browse/QTBUG-82939 which is still open.

As a number of builds use older Qt versions and are affected by the issue, it seems sensible to have this fix, it would just be nice to have a code comment on why this code is here and that it is likely a workaround.

2020-08-29 04:36 UTC, eltonlaw commented
Huh you can't reproduce it? That's weird, on that ticket it says it affects version 5.14.1 and I was able to reproduce on 5.15.0 . Not too sure what's going on.

For the comments, is this alright? 8624880

2020-08-30 20:44 UTC, t-paul commented
I'm still puzzled why it does not happen with my local build. It does happen with the Snap package. I do run Wayland but OpenSCAD is not running as native Wayland app.

Anyway, the patch looks good. Thanks.

2020-08-30 20:44 UTC, t-paul approved these changes

2020-08-30 20:44 UTC, merged

2020-08-30 22:27 UTC, t-paul commented
Hmm, looks like the updated snap does not fix the issue.

2020-08-30 23:21 UTC, MichaelAtOz commented
Should there be Windows builds there?

2020-08-30 23:34 UTC, t-paul commented
Those should show up automatically on the download page at about 8 EDT.

2020-08-31 01:58 UTC, MichaelAtOz commented
Has the build changed or is it sill running?
It used to show e.g.
>  ci/circleci: openscad-appimage-64bit Your tests passed on CircleCI!
Details
ci/circleci: openscad-mxe-32bit Your tests passed on CircleCI!
Details
ci/circleci: openscad-mxe-64bit Your tests passed on CircleCI!
Details

and the files accessed via artifacts.

2020-08-31 08:46 UTC, t-paul commented
Oh, on the PR. Not sure why, but it looks like CircleCI did not see that PR at all. It's been a bit problematic for a while now. Other PRs just start showing "Unauthorized" and fail to run too, but I can trigger manually.

2020-08-31 22:54 UTC, t-paul commented
Looking again at the Snap it does make the editor read-only. It still triggers the autocomplete though, e.g. by typing `cu` / hide editor / typing `b` (or even any other key).

2020-09-01 00:46 UTC, t-paul commented
And it's possible to trigger call-tips via `cube(` + pressing `(`.