warning when a \n is found in use<> or include<>
openscad/openscad pull request #4221
Opened 2022-04-15 08:46 UTC by MichaelPFrey

this is supported syntax:
```
use <test>
use
<test>
use
   <test>
```

This is a quirk of the lexter, not a feature:
```
use
<
test
>
use <
ignored line
used line
>
assert(false);
```
**In release**, it even throws of the line counting.
`[\n\r]` was unhandled, only the last path/filename was used as such.

**In nightly**, I recently fixed the line counting.
Doing so, I specifically added handling of `[\n\r]`.
That feels wrong, as it really is not well defined. But I do not want to make it an error for compatibility.
Making it a warning is a fair compromise.

We could argue, that this is a feature:
```
include<folder/
file.scad>

include
<folder/
file.scad>
```
but it is inconsistent
```
include<folder/
subfoler/
file.scad>

include<folder\
file.scad>

include
<folder\
file.scad>

use
<folder/
file.scad>

use
<folder\
file.scad>
```
that I want to support it for compatibility, but not as a feature.

2022-04-15 14:54 UTC, t-paul requested changes
Sounds good to me. Just noticed a typo in the message.

2022-04-15 14:54 UTC, t-paul commented on src/core/lexer.l
> +							LOG(message_group::Warning,LOCATION(parserlloc),"","new lines in 'include'-statement is not definded - behavior may change in the future");
Typo `definded`. Maybe we could call it `include<>` to make it even clear what's meant?

2022-04-15 14:54 UTC, t-paul commented on src/core/lexer.l
> +							LOG(message_group::Warning,LOCATION(parserlloc),"","new lines 'use'-statement is not definded - behavior may change in the future");
Typo `definded`. Maybe we could call it `use<>` to make it even clear what's meant?

2022-04-15 17:03 UTC, jordanbrown0 commented
I think it's far far more likely that this is a user mistake than intentional, and would be in favor of declaring it an error, especially if that makes anything (e.g. highlighting in the editor) simpler.

2022-04-16 02:01 UTC, MichaelAtOz commented
A path/filename can be very long, [260 chars, or 32K in W10](https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation).

 Formatting with a line break may make sense.

2022-04-16 15:15 UTC, MichaelPFrey commented
> A path/filename can be very long, [260 chars, or 32K in W10](https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation).
> 
> Formatting with a line break may make sense.

I agree in principle, but my issue is, that currently (and looking back to older versions especially releases), the lexter is messy when in comes to line break in use and include. If someone writes a scad file, using a new defintion of line breaks, it breaks compatibility to older version. I would not mind that if the old version would give out an meaning full error. But older version do not give any useful message and even loose track of line count, when they find a line break in between <>.

This is also where my long therm strategy is going: Making it a warning now, so that people that exploit this lexter quirk get warnings, when opening their files in a newer version of openscad (while the scad file still works as before).
Then later, when a release with the warning is established, someone can change the behavior (knowing that users have been warned that the behavior was undefined in the first place).

Side note: I would be careful to give use and include to much of a "non c-style" syntax.

> I think it's far far more likely that this is a user mistake than intentional,

seeing that it caused the line numbering to be off, it is likely a mistake and never (really) noticed before.
The lexter behaves as if it does not know what do to with newlines.

> and would be in favor of declaring it an error,

I think a warning (continue with "best effort") is good enough.
That way, all scad files with that quirk still work fine, but users are encouraged to change their files.
An error (do not continue - fully stopping the lexting) is not necessary.

> especially if that makes anything (e.g. highlighting in the editor) simpler.

The highlighting is fine (for the most part, you can get the syntax highlighting confused while editing, but that is fixed after pressing F5).
Debugging the syntax highlight lexer brought me to this issue in the first place.

The hyperlink indicators are confused, but this is a direct result of the lexter being confused.

2022-04-16 18:08 UTC, MichaelPFrey commented
I add in a `// see merge request #4221` for good measure.
This discussion here is a good reference.

For readers from the future, also see #4211 for context.

That way, it is clear that both the code and the test are a mix of backwards compatibility and provisional improvement in the context of backwards compatibility.

If there is ever a big language- or lexer-overhaul: Feel free to make up a new definition and implement it consistently. Feel free to write a new line number test - all the current line number test wants to be is a regression test based on the current lexer. For a new lexer, it can make sense to disregard the current test.

2022-04-18 15:28 UTC, t-paul commented
Yeah, going directly to error seems excessive here as there's no technical reason to go with warning first. This looks good to me, I would hope multi-line include<> or use<> is not a common thing. If there's unexpected impact we can always reconsider.

2022-04-18 15:28 UTC, t-paul approved these changes

2022-04-18 15:29 UTC, merged