Changes to allow building with Qt 6
openscad/openscad pull request #4904
Opened 2023-12-27 17:27 UTC by cjmayo

With Qt5Compat and without gamepad support.

and Fix slots not matching signals with Qt 6

---

These changes allow me to do a non-experimental build and run OpenSCAD on Qt 6 (and still with Qt 5 too).

N.B. I am really a Python person so do please check carefully - especially the use of QSoundEffect, and I kinda guessed what the return value of `ScadLexer2::description()` should be.

2023-12-27 18:28 UTC, t-paul requested changes
Nice, that looks very promising. The build error on Windows should be easy to resolve by getting the `include` back. If this can provide compatibility with both Qt5 and Qt6 without much trickery that would be great.

I'm trying to get the snapshot builds back, for some reason those did not trigger for the PR.

2023-12-27 18:28 UTC, t-paul commented on src/gui/MainWindow.cc
> -#include <QDesktopWidget>
This is needed for Windows builds.

2023-12-27 18:32 UTC, t-paul commented
CircleCI workflow running at https://app.circleci.com/pipelines/github/openscad/openscad/4450/workflows/6ff4d24a-aae3-48fd-afb5-73ba065e353f

They will likely all show up as fail due to the manual start, but hopefully do the build successfully.

2023-12-27 22:18 UTC, t-paul commented on src/gui/ScintillaEditor.cc
> +#include <QRegExp>
I see, no problem having it if that reduces the needed changes.

2023-12-28 01:57 UTC, t-paul commented on src/gui/MainWindow.cc
> -#include <QDesktopWidget>
Looks promising, according to the docs `QScreen` is available since 5.0, so that should work for both versions too.

2023-12-28 21:07 UTC, t-paul approved these changes
If the new QtGamepad is simpler to setup it might even become usable. I never got it to work well anyway, so lets just wait and see how it will look like if it gets into Qt6.

2023-12-28 21:07 UTC, merged

2023-12-30 21:53 UTC, kintel commented
@cjmayo Out of curiosity, do you have a grander plan/idea/wish for your Qt6 work? I was thinking about starting a tracking ticket for eventually moving to Qt6 as the default, but just wanted to hear about your current ideas.

2023-12-31 17:19 UTC, kintel commented
If you could share the files, that would be awesome. I'll open a ticket and tag you, feel free to dump any knowledge, ideas or experience into that ticket